# UAPI Header export list
no-export-headers += armada_drm.h
no-export-headers += etnaviv_drm.h
no-export-headers += omap_drm.h
no-export-headers += vgem_drm.h
header-y += armada_drm.h
header-y += etnaviv_drm.h
header-y += vgem_drm.h
